### PR TITLE
Mod data stored in the savegame (no more xml and cloud support)

### PR DESCRIPTION
**Pull request by kbytesys**
I've moved the mod data into the savegame.

The old xml data is imported, but the mod will not use it anymore after the first save.

On the "old" mod, if your savegame is broken, you have to delete che traffic manager xml files. Now you can use the "reset data" flag from the options panel.

Please test and approve this changes :smile_cat:

### CODE REVIEW

**Comment by kbytesys** [comment]
Why you reverted this PR?

I don't think that bug reported from steam are related to how the data is loaded.

**Comment by SvetlozarValchev** [comment]
It broke the savegames of all people that used it, irreversibly. Missing textures and overlaying roads might be a null reference error, or wrong set/get of data. It might be a coincidence if one player is saying it, but it is apparent if 15 people post the same issue in 2 hours, when usually I get one comment per day.

**Comment by SvetlozarValchev** [comment]
Last I tested it, it worked fine, but as with most things, a certain common case was not tested, and it breaks the savegames badly.

**Comment by kbytesys** [comment]
If they had the issue on first load, there are no differences from the actual data loading and there are no differences between the MemoryStream and a FileStream in a .net class serializator (also Traffic++ and other mods use this pattern).

There are some bugs on data loading that could affect a different data loading timing?

I see a strange timer on load function that avoids some null reference exception and MemoryStream from the savegame is faster than load data from the file. This could be a test case.

I hope you will investigate more, because I'm unable to recreate issue they reported with my 3 saves with +100k people.

**Pull request merged**
